// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogAPISpec) DeepCopyInto(out *CatalogAPISpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogAPISpec.
func (in *CatalogAPISpec) DeepCopy() *CatalogAPISpec {
	if in == nil {
		return nil
	}
	out := new(CatalogAPISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogAPIStatus) DeepCopyInto(out *CatalogAPIStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogAPIStatus.
func (in *CatalogAPIStatus) DeepCopy() *CatalogAPIStatus {
	if in == nil {
		return nil
	}
	out := new(CatalogAPIStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KScout) DeepCopyInto(out *KScout) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KScout.
func (in *KScout) DeepCopy() *KScout {
	if in == nil {
		return nil
	}
	out := new(KScout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KScout) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KScoutList) DeepCopyInto(out *KScoutList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KScout, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KScoutList.
func (in *KScoutList) DeepCopy() *KScoutList {
	if in == nil {
		return nil
	}
	out := new(KScoutList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KScoutList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KScoutSpec) DeepCopyInto(out *KScoutSpec) {
	*out = *in
	out.CatalogAPI = in.CatalogAPI
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KScoutSpec.
func (in *KScoutSpec) DeepCopy() *KScoutSpec {
	if in == nil {
		return nil
	}
	out := new(KScoutSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KScoutStatus) DeepCopyInto(out *KScoutStatus) {
	*out = *in
	out.CatalogAPI = in.CatalogAPI
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KScoutStatus.
func (in *KScoutStatus) DeepCopy() *KScoutStatus {
	if in == nil {
		return nil
	}
	out := new(KScoutStatus)
	in.DeepCopyInto(out)
	return out
}
